const authServices = require('../Apis/authServices');
const express = require('express');
const router = express.Router();
router.post('/register',authServices.register);
router.post('/uploadProfileImage/:userId',authServices.uploadProfileImage);
router.post('/login',authServices.logIn);
router.delete('/deleteAccount/:userId',authServices.deleteAccount);
router.put('/updateAccount/:userId',authServices.updateAccount);
router.post('/forgetPassword',authServices.forgetPassword);
router.patch('/resetPassword',authServices.resetPassword);
module.exports= router;